Map serialization
AlvinRamoutar/sudoku-api pull request #4
Opened 2020-04-28 20:14 UTC by JoseGeorges8

- Added serialization for puzzle and its dependent models PuzzleOptions, Grid, Cell and Position.
- Removed the cell interface from the Cell class since it wouldn't let me create a private constructor, probably not the best choice but worked for me (Hoping for a suggestion on how to approach this differently). 
- Added a new property in Puzzle to keep track of time when making it a map

2020-04-28 22:22 UTC, JoseGeorges8 commented
@AlvinRamoutar I've updated the PR

2020-04-28 22:25 UTC, AlvinRamoutar commented
Great; will review and get back to you soon

2020-04-29 16:31 UTC, AlvinRamoutar requested changes
Hey @JoseGeorges8 ,

I've made some suggestions, a major one being how we can handle ICell.
You can easily find those ICell-related suggestions by their footer: 
_Part of the 'let's keep ICell' movement ;)_

TO implement these ICell changes, we'd have to change ICell's [constructor](https://github.com/AlvinRamoutar/sudoku-api/blob/111da91d4bda90b4f82d824eb33a254f5aaa222d/lib/src/models/ICell.dart#L12) to the following:
`ICell(this.position, this.isPristine);`

I've ran `serialization_test` successfully.

Let me know what you think - thank you for the mapping contributions!

2020-04-29 16:31 UTC, AlvinRamoutar commented on lib/src/Puzzle.dart
> +  int _timeElapsedInSeconds = 0; // holds the elapsed time for when getting converted to a map
Trying to figure out where/why this exists.
I'm only seeing one write to it, in [Line 47](https://github.com/JoseGeorges8/sudoku-api/blob/95b4dff6533dbff802540617de1e1386a2b328e3/lib/src/Puzzle.dart#L47) of `Puzzle`.

2020-04-29 16:31 UTC, AlvinRamoutar commented on lib/src/Puzzle.dart
> +      throw('Board already generated');
Good catch; could we see an exception implementation in `/src/logic/SudokuException`?
Something simple; just planning for the future.
I.e.:

```
/// Throw whenever [Puzzle] experiences a generation related issue
class GenerationException implements Exception {
  String cause;
  GenerationException(this.cause);
}
```

2020-04-29 16:31 UTC, AlvinRamoutar commented on lib/src/Puzzle.dart
> +  Duration getTimeElapsed() => Duration(seconds: _timeElapsedInSeconds) + _stopwatch.elapsed;
If [Line 47](https://github.com/JoseGeorges8/sudoku-api/blob/95b4dff6533dbff802540617de1e1386a2b328e3/lib/src/Puzzle.dart#L47) ends up being redundant, we can replace with:

```suggestion
   Duration getTimeElapsed() => _stopwatch.elapsed;
```

2020-04-29 16:31 UTC, AlvinRamoutar commented on lib/src/models/Cell.dart
> +class Cell{
```suggestion
class Cell extends ICell {
```

_Part of the 'let's keep ICell' movement ;)_

2020-04-29 16:31 UTC, AlvinRamoutar commented on lib/src/models/Cell.dart
> +
```suggestion

```

_Part of the 'let's keep ICell' movement ;)_

2020-04-29 16:31 UTC, AlvinRamoutar commented on lib/src/models/Cell.dart
> +  Cell(this.position, [this._value = 0]){
```suggestion
  Cell(position, [this._value = 0]) : super(position, true){
```

_Part of the 'let's keep ICell' movement ;)_

2020-04-29 16:31 UTC, AlvinRamoutar commented on lib/src/models/Cell.dart
> +  }
```suggestion
  Cell._({int value,
    bool isPrefill,
    bool isValid,
    bool isMarkup,
    bool isPristine,
    Position position}) : this._isPrefill = isPrefill, this._value = value, this._isValid = isValid, this._isMarkup = isMarkup, super(position, isPristine) {
    _onChange = new StreamController.broadcast();
  }
```

_Part of the 'let's keep ICell' movement ;)_

2020-04-29 21:51 UTC, JoseGeorges8 commented on lib/src/Puzzle.dart
> +  int _timeElapsedInSeconds = 0; // holds the elapsed time for when getting converted to a map
So to get the time elapsed you're using a Stopwatch, and looking through the class I couldn't find a way to add/set time to the stopwatch itself, and if someone wants to continue the puzzle later, the time that already passed should be recorded therefore I thought this variable could hold the timeElapsed up to the point where the map was created/ready to be stored.


- [Line 73](https://github.com/JoseGeorges8/sudoku-api/blob/95b4dff6533dbff802540617de1e1386a2b328e3/lib/src/Puzzle.dart#L73) Assigns the value to the map `time_elapsed_in_seconds`
- [Line 151](https://github.com/JoseGeorges8/sudoku-api/blob/95b4dff6533dbff802540617de1e1386a2b328e3/lib/src/Puzzle.dart#L151) Now gives you the current time passed + the timeElapsed previously
- [Line 66](https://github.com/JoseGeorges8/sudoku-api/blob/95b4dff6533dbff802540617de1e1386a2b328e3/lib/src/Puzzle.dart#L66) retrieves the value from the `time_elapsed_in_seconds` map property and assigns it to the puzzle `_timeElapsedInSeconds ` property

Hopefully this clarifies the where/why property!

2020-04-29 21:54 UTC, JoseGeorges8 commented on lib/src/Puzzle.dart
> +      throw('Board already generated');
Yeah I'll create and update the code to include this

2020-04-29 21:55 UTC, JoseGeorges8 commented on lib/src/Puzzle.dart
> +  Duration getTimeElapsed() => Duration(seconds: _timeElapsedInSeconds) + _stopwatch.elapsed;
Check the comment above about the [Line 47](https://github.com/JoseGeorges8/sudoku-api/blob/95b4dff6533dbff802540617de1e1386a2b328e3/lib/src/Puzzle.dart#L47)

2020-04-29 22:09 UTC, JoseGeorges8 commented
@AlvinRamoutar  Changes have been reviewed and applied 👍Thanks for the suggestions!

2020-04-29 22:52 UTC, AlvinRamoutar approved these changes
Sweet!
Thanks for the clarification regarding `_timeElapsedInSeconds `, let's leave it like that for now until there's a better way we can handle it in the future.
Everything else looks good, `generation_test` and `serialization_test` were successful.

Proceeding with merging - thank you for your contribution @JoseGeorges8 ! 😄

2020-04-29 22:53 UTC, merged