Update Puzzle.dart
AlvinRamoutar/sudoku-api pull request #8
Opened 2020-10-30 10:22 UTC by DeepStyles

hi, I am creating flutter sudoku using your Api, I want this getter to check clock paused or not. its helpful for app if u accept proposal or similar added feature to api.

2020-10-30 13:10 UTC, AlvinRamoutar requested changes

2020-10-30 13:10 UTC, AlvinRamoutar commented on lib/src/Puzzle.dart
> +  bool get isStopClockRunning => _stopwatch.isRunning();
```suggestion
  bool get isStopwatchRunning => _stopwatch.isRunning();
```

Matching the naming of other `Stopwatch` methods.

2020-10-30 13:11 UTC, AlvinRamoutar commented
Hey @DeepStyles ,
Appreciate the suggestion and contribution!
I've recommended a change, just purely syntactical sugar.

Thanks,
Alvin

2020-10-30 13:51 UTC, DeepStyles commented
hey its my first contribution ever thank you...

2020-11-01 09:35 UTC, DeepStyles reviewed
sry, previous line throwing error cause isRunning is a getter, so made that change.

2020-11-07 20:19 UTC, AlvinRamoutar commented
Hey @DeepStyles , will review sometime this weekend. Thanks!

2020-11-09 23:41 UTC, AlvinRamoutar approved these changes
Approved, @DeepStyles .
Tested this change with the following shortcode:

```
    print(puzzle.isStopwatchRunning);
    puzzle.startStopwatch();
    print(puzzle.isStopwatchRunning);
    sleep(Duration(milliseconds: 1374));
    print(puzzle.getTimeElapsed());
    puzzle.stopStopwatch();
    print(puzzle.isStopwatchRunning);
```

2020-11-09 23:42 UTC, merged